### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by user8446** [portapps/hostsman-portable#4]
Is there a changelog for the last two releases? It stopped being listed.

**Comment by crazy-max** [comment]
@user8446 

> Is there a changelog for the last two releases?

[CHANGELOG.md](https://github.com/portapps/hostsman-portable/blob/master/CHANGELOG.md)

> It stopped being listed.

Being listed? Can you clarify?

**Comment by crazy-max** [comment]
If you talk about the [changelog on the official website](http://www.abelhadigital.com/hostsman/release-notes/), yes indeed there is no `4.8.106` release BUT this release can be downloaded here: https://download.fileeagle.com/files/2018/07/HostsMan_4.8.106.zip

**Comment by crazy-max** [comment]
It was previously available at http://hostsman2.it-mate.co.uk/HostsMan_4.8.106.zip
